monday/blog/urls.py
from unicodedata import name
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('<slug>', views.article_detail, name='article_detail'),
    path('article_create/', views.article_create, name='article_create'),
    path('<slug>/edit', views.edit_article, name="article_edit"),
    path('<slug>/delete', views.delete_article, name="article_delete"),
    path('<slug>/like', views.like_article, name="like_article"),
    path('<slug>/dislike', views.dislike_article, name="dislike_article"),
    path('<slug>/comment/<pk>/delete', views.delete_comment, name="delete_comment"),
    path('<slug>/comment/<pk>/edit', views.edit_comment, name="edit_comment"),
]

monday/monday/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include(('blog.urls','monday'),namespace='blog')),
    path('users/',include(('users.urls','monday'),namespace='users')),
    ]+static (settings.STATIC_URL,document_root=settings.STATIC_ROOT)


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

monday/users/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('sign-up/', views.sign_up, name='sign_up'),
    path('sign_in/',views.sign_in, name='sign_in'),
    path('sign_out/',views.sign_out, name='sign_out')
]

monday/blog/models.py
from django.contrib.auth.models import User
from django.db import models


class Article(models.Model):
    title = models.CharField(max_length=255)
    text = models.TextField()
    slug = models.SlugField(unique=True)
    date = models.DateField(auto_now=True)
    thumb = models.ImageField(blank=True, default='image.jpeg')
    author = models.ForeignKey(User, default=None, on_delete=models.CASCADE)
    likes = models.ManyToManyField(User, related_name='article_likes')
    dislikes = models.ManyToManyField(User, related_name='article_dislikes')

    def __str__(self):
        return self.title   

    def snippet(self):
        return f'{self.text[:20]}... read more' 

    def total_likes(self):
        return self.likes.count()

    def total_dislikes(self):
        return self.dislikes.count()      

class Comment(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    body = models.TextField()
    date_added = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.article} - {self.body[:50]}"         

monday/users/models.py
from django.db import models

# Create your models here.

monday/blog/forms.py
from dataclasses import field
from django import forms
from .models import Article, Comment

class ArticleForm(forms.ModelForm):
    title = forms.CharField(widget=forms.TextInput(attrs={'class': 'input'}))
    text = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'textarea', 'size': '40'})
    )
    slug = forms.CharField(widget=forms.TextInput(attrs={'class': 'input'}))

    class Meta:
        model = Article
        fields = ['title', 'text', 'slug', 'thumb']

class CommentForm(forms.ModelForm):
    body = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'textarea',
        'size': '40',
        'placeholder': 'Write your comment here...'
    }))

    class Meta:
        model = Comment
        fields = ['body', ]

monday/users/forms.py
from dataclasses import field
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User

class SignUpForm(UserCreationForm):
    username = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'input'}),
        label='Create any name'
    )
    password1 = forms.CharField(
        widget=forms.PasswordInput(attrs={'class': 'input'}),
        label='Create any password'
    )
    password2 = forms.CharField(
        widget=forms.PasswordInput(attrs={'class': 'input'}),
        label='Rewrite password'
    )

    class Meta:
        model = User
        fields = ['username', 'password1', 'password2']


class SignInForm(AuthenticationForm):
    username = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'input'}),
        label='type your username'
    )
    password = forms.CharField(
        widget=forms.PasswordInput(attrs={'class': 'input'}),
        label='Type password'
    )

    class Meta:
        model = User
        fields = ['username', 'password',]

monday/blog/views.py
from re import search
from django.shortcuts import render, redirect 
from .models import Article, Comment
from .forms import ArticleForm, CommentForm
from django.contrib.auth.decorators import login_required
from django.db.models import Q


@login_required(login_url='/users/sign_in')
def home(request):
    search = request.GET.get('input')
    print(search)
    articles = Article.objects.all()
    articles = articles.filter(Q(title__icontains=search) | Q(text__icontains=search)) if search else articles
    return render(request, 'home.html', {'articles': articles})


def article_detail(request, slug):
    article = Article.objects.get(slug=slug)
    if request.method == 'POST':
       form = CommentForm(request.POST)
       if form.is_valid():
            instance = form.save(commit=False)
            instance.user = request.user
            instance.article = article
            instance.save()
            return redirect('blog:article_detail', slug=slug)
    form = CommentForm()      
    return render(request, 'article_detail.html', {'article': article, 'form': form})

def article_create(request):
    form = ArticleForm(request.POST, request.FILES)
    if request.method == 'POST' and form.is_valid():
        instance = form.save(commit=False)
        instance.author = request.user
        instance.save()
        return redirect('blog:home')
    form = ArticleForm()     
    return render(request, 'article_create.html', {'form': form})

def edit_article(request, slug):
    article = Article.objects.get(slug=slug)
    form = ArticleForm(request.POST or None, request.FILES or None, instance=article)
    if form.is_valid():
        form.save()
        print(slug)
        return redirect('blog:article_detail', slug=request.POST.get('slug'))
    return render(request, 'edit_article.html', {'form': form, 'article': article})    


def delete_article(request, slug):
    article = Article.objects.get(slug=slug)
    if request.method == 'POST':
        article.delete()
        return redirect('blog:home')
    return render(request, 'delete_article.html', {'article': article})        


def like_article(request, slug):
    article = Article.objects.get(slug=slug)
    if request.user not in article.likes.all():
        article.likes.add(request.user)
        article.dislikes.remove(request.user)
    elif request.user in article.likes.all():
        article.likes.remove(request.user)
    return redirect('blog:article_detail', slug=slug) 


def dislike_article(request, slug):
    article = Article.objects.get(slug=slug)
    if request.user not in article.dislikes.all():
        article.dislikes.add(request.user)
        article.likes.remove(request.user)
    elif request.user in article.dislikes.all():
        article.dislikes.remove(request.user)
    return redirect('blog:article_detail', slug=slug) 


def delete_comment(request, pk, slug):
    comment = Comment.objects.get(pk=pk)
    if request.method == 'POST':
        comment.delete()
        return redirect('blog:article_detail', slug=slug)
    return render(request, 'delete_comment.html', {'comment': comment})       

def edit_comment(request, pk, slug):
    comment = Comment.objects.get(pk=pk)
    form = CommentForm(request.POST or None, instance=comment)
    if form.is_valid():
        form.save()
        return redirect('blog:article_detail', slug=slug)
    return render(request, 'edit_comment.html', {'form': form, 'article': comment.article})    

monday/users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login, logout
from .forms import SignInForm, SignUpForm

def sign_up(request):
    form = SignUpForm(request.POST)
    if form.is_valid():
        form.save()
        return redirect('users:sign_in')
    form = SignUpForm()
    return render(request, 'sign_up.html', {'form': form})    


def sign_in(request):
    if request.method == 'POST':
        form = SignInForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            return redirect('blog:home')
    form = SignInForm()
    return render(request, 'sign_in.html', {'form': form})    


def sign_out(request):
    logout(request)
    return redirect('users:sign_in')

monday/blog/templates/article_create.html
{% extends "base_layout.html" %}
{% block content %}
    <form 
        class="site-form has-background-light"   
        action="{% url 'blog:article_create'%}"
        method='post'
        enctype="multipart/form-data">
        {% csrf_token %} 
        {{ form }} 
        <div class="has-text-centered my-2">
            <button type="submit" class="button is-success">Отправить</button>
            <a href="{% url 'blog:home' %}" class="button is-danger">
                Отмена
            </a>
        </div>
    </form>
{% endblock %}    

monday/blog/templates/article_detail.html
{% extends 'base_layout.html' %}
{% load static from static %}

{% block content %}
<div class="box">
    <div class="has-text-right">
        {% if user == article.author %}
        <a href="{% url 'blog:article_edit' article.slug %}" class="button is-info">
            <ion-icon name="create-outline"></ion-icon>
        </a>
        <a href="{% url 'blog:article_delete' article.slug %}" class="button is-danger">
            <ion-icon name='trash-outline'></ion-icon>
        </a>
        {% else %}
        <p class="content has-text-grey">
            You can't not edit or delete this post
        </p>
        {% endif %}
    </div>

    <div class="title has-text-dark has-text-centered">
        {{ article }}
    </div>
    <img src="{{ article.thumb.url }}" alt="" class="image is-centered" style="min-width: 100%; border-radius: 5px;">
    <div class="subtitle has-text-dark has-text-centered">
        {{ article.text }}
    </div>


    {% if user not in article.likes.all and user not in article.dislikes.all %}
    <div class="columns">
        <div class="column is-1">
            <form action="{% url 'blog:like_article' article.slug %}" method="post" class="has-text-right">
                {% csrf_token %}
                <button type="submit" class="button">
                    <ion-icon name='thumbs-up-outline'></ion-icon>
                    <span class="ml-2">{{ article.total_likes}}</span>

                </button>
            </form>
        </div>
        <div class="column is-1">
            <form action="{% url 'blog:dislike_article' article.slug %}" method="post" class="has-text-right">
                {% csrf_token %}
                <button type="submit" class="button">
                    <ion-icon name='thumbs-down-outline'></ion-icon>
                    <span class="ml-2">{{ article.total_dislikes}}</span>
                </button>
            </form>
        </div>
    </div>
    {% endif %}


    {% if user in article.likes.all and user not in article.dislikes.all %}
    <div class="columns">
        <div class="column is-1">
            <form action="{% url 'blog:like_article' article.slug %}" method="post" class="has-text-right">
                {% csrf_token %}
                <button type="submit" class="button is-success">
                    <ion-icon name='thumbs-up-outline'></ion-icon>
                    <span class="ml-2">{{ article.total_likes}}</span>
                </button>
            </form>
        </div>
        <div class="column is-1">
            <form action="{% url 'blog:dislike_article' article.slug %}" method="post" class="has-text-right">
                {% csrf_token %}
                <button type="submit" class="button">
                    <ion-icon name='thumbs-down-outline'></ion-icon>
                    <span class="ml-2">{{ article.total_dislikes }}</span>
                </button>
            </form>
        </div>
    </div>
    {% endif %}

    {% if user not in article.likes.all and user in article.dislikes.all %}
    <div class="columns">
        <div class="column is-1">
            <form action="{% url 'blog:like_article' article.slug %}" method="post" class="has-text-right">
                {% csrf_token %}
                <button type="submit" class="button">
                    <ion-icon name='thumbs-up-outline'></ion-icon>
                    <span class="ml-2">{{ article.total_likes}}</span>
                </button>
            </form>
        </div>
        <div class="column is-1">
            <form action="{% url 'blog:dislike_article' article.slug %}" method="post" class="has-text-right">
                {% csrf_token %}
                <button type="submit" class="button is-danger">
                    <ion-icon name='thumbs-down-outline'></ion-icon>
                    <span class="ml-2">{{ article.total_dislikes }}</span>
                </button>
            </form>
        </div>
    </div>
    {% endif %}
    {% if not article.comment_set.all %}
    <div class="has-text-centered has-text-grey-light is-5 mx-3">
        No comments yet. Be first to leave...
    </div>
    {% else %}
    <div class="title has-text-centered is-3 mb-6"></div>
    {% for comment in article.comment_set.all %}
    <article class="message is-info">
        <div class="message-header">
            {% if user == comment.user %}
            Added by you at {{ comment.user }} at {{ comment.date_added }}
            <div class="has-text-right is-size-5">
                <a href="{% url 'blog:edit_comment' slug=article.slug pk=comment.pk %}" style="text-decoration: none"
                    class="button is-success">
                    <ion-icon name="create-outline"></ion-icon>
                </a>
                <a href="{% url 'blog:delete_comment' slug=article.slug pk=comment.pk %}" style="text-decoration: none"
                    class="button is-danger">
                    <ion-icon name="trash-outline"></ion-icon>
                </a>
            </div>  
            {% else %}
            Added by {{ comment.user}} at {{ comment.user }} at {{ comment.date_added }}
            {% endif %}
        </div>
        <div class="message-body">{{ comment.body }}</div>
    </article>
    {% endfor %}
    {% endif %}


    <div class="has-text-grey is-size-6 has-text-right is-italic">
        <p class="datetime">Date of publication: {{ article.date }}</p>
        {% if user == article.author %}
        <p class="content">Published by you</p>
        {% else %}
        <p class="content">Published by: {{ article.author }}</p>
        {% endif %}
    </div>
    <form class="comment" enctype="multipart/form-data" method="post">
        {% csrf_token %}
        {{ form }}
        <button class="button is-success is-fullwidth mt-3" type="submit">
            Submit
        </button>
    </form>
</div>
{% endblock %}

monday/blog/templates/base_layout.html
{% load static from static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <link rel="stylesheet" href="{% static 'bulma.css' %}">
    <script type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"></script>
    <script nomodule src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"></script>
</head>
<body>

<section class="hero has-background-info is-fullheight">
    <div class="hero-head">
        <header class="navbar">
            <div class="container">
                <div class="navbar-brand">
                    <a class="navbar-item" href="/">
                        <img src="https://macademy.uz/assets/img/monday.svg" width="100" alt="Logo">
                    </a>
                    <span class="navbar-burger" data-target="navbarMenuHeroC">
                        <span></span>
                        <span></span>
                        <span></span>
                    </span>
                </div>
                {% if user.is_authenticated %}
                <div id="navbarMenuHeroC" class="navbar-menu">
                    <div class="navbar-start">
                        <span class="navbar-item">
                            <a 
                                href="{% url 'blog:article_create' %}"
                                class="button is-info is-outlined is-inverted">
                                <span class="mr-2">
                                    <icon-icon name='book-outlined'></icon-icon>
                                </span>
                                <span>
                                    Создать пост
                                </span>
                            </a>
                        </span>
                    </div>
                    <div class="navbar-end">
                        <form action="{% url 'blog:home' %}" method="get">
                            <div class="field has-addons mt-4 mr-2">
                                <div class="control">
                                    <input type="search" class="input" placeholder="Find an article" name="input">
                                </div>
                                <div class="control">
                                    <button class="button is-success" type="submit">Search</button>
                                </div>
                            </div>
                        </form>
                        <a class="navbar-item button my-4 mx-1">
                            Welcome: {{ user }}
                        </a>
                        <span class="navbar-item">
                            <a href="{% url 'users:sign_out' %}" class="button is-warning">Sign out</a>
                        </span>
                    </div>
                {% endif %}
                </div>
            </div>
        </header>
    </div>
    <div class="hero-body">
        {% block content %}
        {% endblock %}
    </div>
</section>
</body>
</html>

monday/blog/templates/delete_article.html
{% extends 'base_layout.html' %}

{% block content %}
    <form method="post" class="site-form has-background-light" style="margin-top: 200px;">
        {% csrf_token %}
        <p class="content has-text-centered is-size-4 mb-4">
            Are you sure you want to delete post "{{ article }}"?
        </p>
        <div class="has-text-centered">
            <button class="button is-primary" type="submit">Yes</button>
            <a href="{% url 'blog:article_detail' article.slug %}" class="button is-danger">No</a>
        </div>
    </form>

{% endblock %}    

monday/blog/templates/delete_comment.html
{% extends 'base_layout.html' %}

{% block content %}
<form class="site-form has-background-light" method="post">
    {% csrf_token %}
    <p class="title is-size-4 mb-4">
        Вы действительно хотите удалить комментарий?
    </p>
    <div class="has-text-centered">
        <button class="button is-success" type="submit">
            Потвердить
        </button>
        <a class="button is-danger" href="{% url 'blog:article_detail' comment.article.slug %}">
            Отмена
        </a>
    </div>
</form>
{% endblock %}

monday/blog/templates/edit_article.html
{% extends 'base_layout.html' %}

{% block content %}
    <form class="site-form has-background-light" method="post" enctype="multipart/form-data">
        <h2 class="title is-size-2 has-text-centered">Update Article</h2>
        {% csrf_token %}
        {{ form }}
        <div class="has-text-centered my-4">
            <button class="button is-success" type="submit">Submit</button>
            <a href="{% url 'blog:article_detail' article.slug %}" class="button is-danger">
                Back
            </a>
        </div>
    </form>
{% endblock %}    

monday/blog/templates/edit_comment.html
{% extends 'base_layout.html' %}
{% block content %}
<form class="site-form has-background-light" method="post" enctype="multipart/form-data" style="margin-top: 100px;">
    <div class="title is-2 has-text-centered">
        Изменить комментарий
    </div>
    {% csrf_token %}
    {{ form }}
    <div class="has-text-centered mt-4">
        <button class="button is-success" type="submit">
            Потвердить
        </button>
        <a class="button is-danger" href="{% url 'blog:article_detail' article.slug %}">
            Отмена
        </a>
    </div>
</form>
{% endblock %}

monday/blog/templates/home.html
{% extends "base_layout.html" %}

{% block content %}
<div class="container">
    <div class="columns is-centered is-multiline">
        {% for article in articles %}
        <div class="column is-3">
            <a href="{% url 'blog:article_detail' article.slug %}">
                <div class="card has-text-centered">
                    <div class="card-content">
                        <div class="media">
                            <div class="media-content">
                                <p class="title has-text-dark is-2">
                                    {{ article }}
                                </p>
                                {% if user == article.author %}
                                <p class="subtitle is-4 has-text-grey">by you</p>
                                {% else %}
                                <p class="subtitle is-4 has-text-grey">by {{ article.author }}</p>
                                {% endif %}
                            </div>
                        </div>
                        <div class="content">
                            {{ article.snippet }}
                            <br>
                            <div>{{ article.date }}</div>
                            <div class="columns">
                                <div class="column is-2">
                                    <div class="columns is-gapless">
                                        <div class="column">
                                            <ion-icon name="thumbs-up-outline" class="mt-1"></ion-icon>
                                        </div>
                                        <div class="column">
                                            <span class="ml-4">{{ article.total_likes }}</span>
                                        </div>
                                    </div>
                                </div>

                                <div class="column is-2">
                                    <div class="columns is-gapless">
                                        <div class="column">
                                            <ion-icon name="thumbs-down-outline" class="mt-1"></ion-icon>
                                        </div>
                                        <div class="column">
                                            <span class="ml-2">{{ article.total_dislikes}}</span>
                                        </div>
                                    </div>
                                </div>
                                <div class="column is-2">
                                    <div class="columns is-gapless">
                                        <div class="column">
                                            <ion-icon name="clipboard-outline" class="mt-1"></ion-icon>
                                        </div>
                                        <div class="column">
                                            <span class="ml-2">{{ article.comment_set.count}}</span>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </a>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

monday/users/templates/sign_in.html
{% extends 'base_layout.html' %}

{% block content %}
<form class="site-form has-text-centered has-background-light" method="post">
    <div class="title is-2">Sign in</div>
    {% csrf_token %}
    {% for field in form %}
    <div class="field">
        <label for="{{ field.id_for_label }}" class="label">
            {{ field.label }}
        </label>
        {{ field }}
    </div>
    {% endfor %}
    <button class="button is-success is-fullwidth mt-4" type="submit">
        Sign in
    </button>
    <p class="has-text-centered has-text-grey-light mt-2">
        Don't have an account?
        <br>
        <a href="{% url 'users:sign_up' %}">Move to register page</a>
    </p>
</form>
{% endblock %}

monday/users/templates/sign_up.html
{% extends 'base_layout.html'%}

{% block content %}
<form class="site-form has-text-centered has-background-light" method="post" style="margin-top: 120px">
    <div class="title is-size-2 has-text-centered">
        Sign up
    </div>
    {% csrf_token %}
    {% for field in form %}
        <div class="field">
            <label for="{{ field.id_for_label }}" class="label">
                {{ field.label }}
            </label>
            {{ field }}
        </div>
    {% endfor %}
    <br>
    <button type="submit" class="button is-success">Register</button>
    <p class="has-text-centered has-text-grey-light mt-2">
        Already have an account?
        <br>
        <a href="{% url 'users:sign_in' %}">Move to login page</a>
    </p>
</form>
{% endblock %}